FROM node:20-alpine as build-stage
WORKDIR /usr/src/app

# Install dependencies
COPY frontend/package*.json ./frontend/
COPY backend/package*.json ./backend/

RUN cd frontend && npm ci
RUN cd backend && npm ci

COPY frontend ./frontend
COPY backend ./backend

# Build the React frontend
RUN cd frontend && npm run build
RUN cd backend && npm run build

WORKDIR /usr/src/app/backend
CMD ["npm", "start"]