POST http://localhost:8000/api/position
Content-Type: application/json

{
    "name": "Webbitiimi",
    "description": "Webbitiimi ylläpitää ja kehittää killan IT-palveluita",
    "seats": "8-12",
    "election.id": 1
}