import { Kysely } from 'kysely'


// This migration adds the ON DELETE CASCADE into read_receipts.application_id
// which was missing in the last migration. This error meant that applications
// with read receipts couldn't be deleted due to violation of the foreign key 
// constraint. Note that the constraint name 'read_receipts_application_id_fkey'
// is auto-generated by kysely and could be found with psql describe table.

export async function up(db: Kysely<any>): Promise<void> {
    await db.schema
        .alterTable('read_receipts')
        .dropConstraint('read_receipts_application_id_fkey')
        .execute()

    await db.schema
        .alterTable('read_receipts')
        .addForeignKeyConstraint('read_receipts_application_id_fkey', ['application_id'], 'application', ['id'])
        .onDelete('cascade')
        .execute()
}

export async function down(db: Kysely<any>): Promise<void> {
    await db.schema
        .alterTable('read_receipts')
        .dropConstraint('read_receipts_application_id_fkey')
        .execute()

    await db.schema
        .alterTable('read_receipts')
        .addForeignKeyConstraint('read_receipts_application_id_fkey', ['application_id'], 'application', ['id'])
        .execute()
}