import type { Metadata } from 'next'

import '../globals.css'
import { ThemeProvider } from '@/components/ThemeProvider'
import { SidebarProvider } from "@/components/ui/sidebar"
import { BreadcrumbProvider } from '@/lib/hooks/useBreadcrumb'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head />
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className="[--header-height:calc(--spacing(16))]">
                        <SidebarProvider className="flex flex-col">
                            <BreadcrumbProvider>
                                {children}
                            </BreadcrumbProvider>
                        </SidebarProvider>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    )
}